#!/bin/bash

echo "Cassandra node configuration:"
echo $CASS_SEEDS
echo $CASS_TOKEN
echo $CASS_LOCAL_IP

sed -i "s/{{INITIAL_TOKEN}}/$CASS_TOKEN/g" /opt/cassandra/conf/cassandra.yaml
sed -i "s/{{SEEDS}}/$CASS_SEEDS/g" /opt/cassandra/conf/cassandra.yaml
sed -i "s/{{LOCAL_IP}}/$CASS_LOCAL_IP/g" /opt/cassandra/conf/cassandra.yaml
sed -i "s/{{LOCAL_IP}}/$CASS_LOCAL_IP/g" /opt/cassandra/conf/cassandra-env.sh

HOST=`hostname`
echo "127.0.0.1 $HOST" >> /etc/hosts

echo "eureka.port=8080" >> /opt/tomcat/conf/cataline.properties
echo "eureka.name=cassandra" >> /opt/tomcat/conf/cataline.properties

/opt/tomcat/bin/catalina.sh start

/opt/cassandra/bin/cassandra -f
