#!/bin/bash

source env.sh

CASS1=$(get_next_ip "192.168.0.200" 11)
CASS2=$(get_next_ip "192.168.0.200" 12)
CASS_SEEDS="$CASS1,$CASS2"
TOKEN1=0
TOKEN2=-9223372036854775808

C1=$(docker run -d -e "CASS_SEEDS=$CASS1" -e "CASS_TOKEN=$TOKEN1" -e "CASS_LOCAL_IP=$CASS1" jlewallen/cassandra)
./unionize.sh $PUBLIC_BRIDGE $C1 $CASS1

C2=$(docker run -d -e "CASS_SEEDS=$CASS1" -e "CASS_TOKEN=$TOKEN2" -e "CASS_LOCAL_IP=$CASS2" jlewallen/cassandra)
./unionize.sh $PUBLIC_BRIDGE $C2 $CASS2
