from jlewallen/tomcat

maintainer Jacob Lewallen

add eureka-server-1.1.103-SNAPSHOT.war /opt/tomcat/webapps/eureka.war
add server.xml /opt/tomcat/conf/server.xml

expose 80

entrypoint /opt/tomcat/bin/start

