#!/bin/bash

echo "Cassandra node configuration:"
echo $CASS_SEEDS
echo $CASS_TOKEN
echo $CASS_LOCAL_IP

sed -i "s/{{INITIAL_TOKEN}}/$CASS_TOKEN/g" /opt/cassandra/conf/cassandra.yaml
sed -i "s/{{SEEDS}}/$CASS_SEEDS/g" /opt/cassandra/conf/cassandra.yaml
sed -i "s/{{LOCAL_IP}}/$CASS_LOCAL_IP/g" /opt/cassandra/conf/cassandra.yaml

HOST=`hostname`
echo "127.0.0.1 $HOST" >> /etc/hosts

/opt/cassandra/bin/cassandra -f
