#!/bin/bash

set -e

BASE=http://172.17.42.1:5000

FILE=/tmp/user-data
URL=$BASE/my/user-data
if curl -f -s -o /dev/null --head $URL; then
  curl -f -s $URL | tee $FILE
  . $FILE
else
  echo "No user-data"
fi

FILE=/opt/tomcat/conf/catalina.properties
URL=$BASE/my/catalina.properties
if curl -f -s -o /dev/null --head $URL; then
  curl -f -s $URL | tee -a $FILE
else
  echo "No catalina.properties"
fi
